cam_config:
  cam_dist: 1.6
  cam_pitch: -37.40
  cam_target:
  - -0.29
  - -0.56
  - -0.
  cam_yaw: 152.40
startOrientation:
- 0
- 0
- 0
startPos:
- 0
- 0
- 0.5
gui: True
fps: 120
init_state:
  jointPos: #theta, alpha
  - 0
  - 0
  jointVel: #thetad, alphad
  - 0
  - 0
data_path:
  images: "images"
  videos: "videos"
  robot_data: "robot_data"
sim:
  horizon: 1000
  video_recording: False
fourier_config:
  order: 5
  duration: 10 # the overall time for trajectory generation
maxForceLimits:
- 1000.0
- 0.0
